# files parameters
csv_reads: './test_data_single/test_csv_single.txt'  # './test_data/test_csv.txt' './test_data_single/test_csv_single.txt'
outputDir: './results'
genomeFastaFile: './genome_files/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa'
transcriptFastaFile: './genome_files/Caenorhabditis_elegans.WBcel235.cdna.all.fa'
annotationsGTFFile: './genome_files/Caenorhabditis_elegans.WBcel235.115.gtf'
annotationsGFF3File: './genome_files/Caenorhabditis_elegans.WBcel235.115.gff3'

# which tools to use for each process
trimming: 'trim_galore'  # available options are: 'trimmomatic', 'bbduk', 'trim_galore'
aligner: 'star'  # available options are: 'star', 'hisat2', 'none'
quantifier: 'htseq-count'  # available options are: 'htseq-count', 'featureCounts', 'salmon-quasi-mapping-mode', 'kallisto', 'rsem'
splicingAnalyzer: 'none'  # available options are: 'majiq', 'rMats', 'suppa2', 'whippet'

# Specify whether reads are paired or single end
paired_end: false

# Choose whether to run Fastqc before and/or after trimming
run_fastqc_before_trimming: false
run_fastqc_after_trimming: false

#--------------------------- Trimmomatic parameters ---------------------------#
# Change the value for any trimming step (from none) for it to be included. Make sure to have at least one trimming option active, otherwise there will be an error.
# If you want to use ILLUMINACLIP command, then at least these three parameters need to have values: <seed_mismatches>, <palindrome_clip_threshold>, <simple_clip_threshold>
# If you want to use SLIDINGWINDOW command, then both <window_size> and <required_quality> need ot have values.
base_quality_encoding: 'phred33'
adapters_file: 'TruSeq3-SE.fa'
seed_mismatches: 2
palindrome_clip_threshold: 30
simple_clip_threshold: 10
min_adapter_length_palindrome: null
keepbothreads: null
window_size: 4
required_quality: 15
leading: 3
trailing: 3
headcrop: null
tailcrop: null
crop: null
target_length: null
strictness: null
minlen: 36
maxlen: null
avgqual: null
bases: null
min_count: null
max_count: null


#--------------------------- Bbduk parameters ---------------------------#
# Input parameters
qin: 'auto'
reads: -1
samplerate: 1
# Processing parameters
k: 27
rcomp: 't'
maskmiddle: 't'
minkmerhits: 1
minkmerfraction: 0.0
mincovfraction: 0.0
hammingdistance: 0
qhdist: 0
editdistance: 0
hammingdistance2: 0
qhdist2: 0
editdistance2: 0
forbidn: 'f'
# Trimming/filtering/masking parameters
ktrim: 'f'
ktrimtips: 0
maskfullycovered: 'f'
mink: 0
qtrim: 'f'
trimq: 6
minlength: 10
minlengthfraction: 0
minavgquality: 0
minbasequality: 0
maxns: -1
minconsecutivebases: 0
trimpad: 0
trimbyoverlap: 'f'
strictoverlap: 't'
minoverlap: 14
mininsert: 40
trimpairsevenly: 'f'
forcetrimleft: 0
forcetrimright: 0
forcetrimright2: 0
forcetrimmod: 0
restrictleft: 0
restrictright: 0
mingc: 0
maxgc: 1
tossjunk: 'f'


#--------------------------- Trim-Galore parameters ---------------------------#
quality: 20
quality_encoding: 'phred33'  # options: phred33 or phred64
adapter_sequence_1: null  # Or specify the sequence, for example 'GATCGTCGGACT'
adapter_sequence_2: null  # This is ignored in single-end reads. If not specified for paired-end reads, <adapter_sequence_1> will be applied on both reads.
specific_adapters: 'illumina'  # options are: 'illumina', 'stranded_illumina', 'nextera', 'small_rna', 'bgiseq'. Can only be none if adapter_sequence_1 and/or adapter_sequence_2 are specified
max_length: null
stringency: 1
error_rate: 0.1
length: 20
maxn: null
trim_n: false  # either true or false
trim_1: false  # either true or false
clip_R1: null
clip_R2: null
three_prime_clip_R1: null
three_prime_clip_R2: null
nextseq_quality: null  # only specify the qualty with nextseq and novaseq reads (replaces <quality> parameter)
hardtrim5: null
hardtrim3: null


#--------------------------- STAR parameters ---------------------------#
# Run parameters
runRNGseed: 777
# Genome Indexing Parameters - only used with –runMode genomeGenerate
genomeChrBinNbits: 18
genomeSAindexNbases: 12
genomeSAsparseD: 1
genomeSuffixLengthMax: -1
# Splice Junctions Database
sjdbGTFfeatureExon: 'exon'
sjdbGTFtagExonParentTranscript: 'transcript_id'
sjdbGTFtagExonParentGene: 'gene_id'
sjdbGTFtagExonParentGeneName: 'gene_name'
sjdbGTFtagExonParentGeneType: 'gene_type gene_biotype'
sjdbOverhang: 100
sjdbScore: 2
sjdbInsertSave: 'Basic'
readMapNumber: -1
readMatesLengthsIn: 'NotEqual'
readQualityScoreBase: 33
# Read Clipping
clipAdapterType: 'Hamming'
clip3pNbases: 0
clip3pAdapterSeq: null
clip3pAdapterMMp: 0.1
clip3pAfterAdapterNbases: 0
clip5pNbases: 0
# Output: General
outReadsUnmapped: 'None'
outQSconversionAdd: 0
outMultimapperOrder: 'Old_2.4'
# Output: SAM and BAM
outSAMmode: 'Full'
outSAMstrandField: 'None'
outSAMattributes: 'Standard'
outSAMattrIHstart: 1
outSAMunmapped: 'None'
outSAMprimaryFlag: 'OneBestScore'
outSAMreadID: 'Standard'
outSAMmapqUnique: 255
outSAMflagOR: 0
outSAMflagAND: 65535
outSAMmultNmax: -1
outSAMtlen: 1
outBAMcompression: 1
# Output Filtering
outFilterType: 'Normal'
outFilterMultimapScoreRange: 1
outFilterMultimapNmax: 10
outFilterMismatchNmax: 10
outFilterMismatchNoverLmax: 0.3
outFilterMismatchNoverReadLmax: 1.0
outFilterScoreMin: 0
outFilterScoreMinOverLread: 0.66
outFilterMatchNmin: 0
outFilterMatchNminOverLread: 0.66
outFilterIntronMotifs: 'None'
outFilterIntronStrands: 'RemoveInconsistentStrands'
# Output Filtering: Splice Junctions
outSJfilterReads: 'All'
outSJfilterOverhangMin: '30 12 12 12'
outSJfilterCountUniqueMin: '3 1 1 1'
outSJfilterCountTotalMin: '3 1 1 1'
outSJfilterDistToOtherSJmin: '10 0 5 10'
outSJfilterIntronMaxVsReadN: '50000 100000 200000'
# Scoring
scoreGap: 0
scoreGapNoncan: -8
scoreGapGCAG: -4
scoreGapATAC: -8
scoreGenomicLengthLog2scale: -0.25
scoreDelOpen: -2
scoreDelBase: -2
scoreInsOpen: -2
scoreInsBase: -2
scoreStitchSJshift: 1
# Alignments and Seeding
seedSearchStartLmax: 50
seedSearchStartLmaxOverLread: 1.0
seedSearchLmax: 0
seedMultimapNmax: 10000
seedPerReadNmax: 1000
seedPerWindowNmax: 50
seedNoneLociPerWindow: 10
seedSplitMin: 12
seedMapMin: 5
alignIntronMin: 21
alignIntronMax: 0
alignMatesGapMax: 0
alignSJoverhangMin: 5
alignSJstitchMismatchNmax: '0 -1 0 0'
alignSJDBoverhangMin: 3
alignSplicedMateMapLmin: 0
alignSplicedMateMapLminOverLmate: 0.66
alignWindowsPerReadNmax: 10000
alignTranscriptsPerWindowNmax: 100
alignTranscriptsPerReadNmax: 10000
alignEndsType: 'Local'
alignEndsProtrude: '0 ConcordantPair'
alignSoftClipAtReferenceEnds: 'Yes'
alignInsertionFlush: 'None'
# Paired-End reads
peOverlapNbasesMin: 0
peOverlapMMp: 0.01
# Windows, Anchors, Binning
winAnchorMultimapNmax: 50
winBinNbits: 16
winAnchorDistNbins: 9
winFlankNbins: 4
winReadCoverageRelativeMin: 0.5
winReadCoverageBasesMin: 0
quantMode: null
quantTranscriptomeBAMcompression: 1
quantTranscriptomeSAMoutput: 'BanSingleEnd_BanIndels_ExtendSoftclip'


#--------------------------- HTSEQ-COUNT parameters ---------------------------#
max_reads_in_buffer: 30000000
stranded: 'no'
minaqual: 10
feature_type: 'exon'
id_attribute: 'gene_id'
additional_attributes: null  # specify the additional attributes as a list of strings, e.g. ['gene_name', 'exon_number']
mode: 'union'
nonunique_mode: 'none'
secondary_alignments: 'score'
supplementary_alignments: 'score'
add_chromosome_info: false


# HISAT2 parameters
hisat2_index_prefix: 'genome'

# SALMON parameters
kmer_size: 31

# KALLISTO parameters
num_bootstrap_samples: 0
mean_fragment_length: 200  # estimated for paired-end reads, used only for single-end reads
sd_fragment_length: 70  # estimated for single-end reads, used only for single-end reads

# General Splicing parameters
individualSplicingAnalysis: true
differentialSplicingAnalysis: true

#RSEM parameters
rsem_index_prefix: 'rsem_reference'
strandedness: 'none'
fragment_length_mean: -1  # used only for single-end reads, change the value if you know it
fragment_length_sd: 0  # used only for single-end reads, change the value if you know it

# rMats parameters
read_length: 100
