# files parameters
csv_reads: './test_data_single/test_csv_single.txt'  # './test_data/test_csv.txt' './test_data_single/test_csv_single.txt'
outputDir: './results'
genomeFastaFile: './genome_files/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa'
transcriptFastaFile: './genome_files/Caenorhabditis_elegans.WBcel235.cdna.all.fa'
annotationsGTFFile: './genome_files/Caenorhabditis_elegans.WBcel235.115.gtf'
annotationsGFF3File: './genome_files/Caenorhabditis_elegans.WBcel235.115.gff3'

# which tools to use for each process
trimming: 'trim_galore'  # available options are: 'trimmomatic', 'bbduk', 'trim_galore'
aligner: 'hisat2'  # available options are: 'star', 'hisat2', 'none'
quantifier: null  # available options are: 'htseq-count', 'featureCounts', 'salmon-quasi-mapping-mode', 'kallisto', 'rsem'
splicingAnalyzer: 'rMats'  # available options are: 'majiq', 'rMats', 'suppa2', 'whippet'

# Specify whether reads are paired or single end
paired_end: false

# Choose whether to run Fastqc before and/or after trimming
run_fastqc_before_trimming: false
run_fastqc_after_trimming: false

# Bowtie2 filtering parameters
filter_contaminants: false
contaminants: ['./genome_files/Caenorhabditis_elegans.WBcel235.ncrna.fa.gz']  # provide as a list of paths for the contaminant files

#--------------------------- Trimmomatic parameters ---------------------------#
# Change the value for any trimming step (from none) for it to be included. Make sure to have at least one trimming option active, otherwise there will be an error.
# If you want to use ILLUMINACLIP command, then at least these three parameters need to have values: <seed_mismatches>, <palindrome_clip_threshold>, <simple_clip_threshold>
# If you want to use SLIDINGWINDOW command, then both <window_size> and <required_quality> need ot have values.
base_quality_encoding: 'phred33'
adapters_file: 'TruSeq3-SE.fa'
seed_mismatches: 2
palindrome_clip_threshold: 30
simple_clip_threshold: 10
min_adapter_length_palindrome: null
keepbothreads: null
window_size: 4
required_quality: 15
leading: 3
trailing: 3
headcrop: null
tailcrop: null
crop: null
target_length: null
strictness: null
minlen: 36
maxlen: null
avgqual: null
bases: null
min_count: null
max_count: null


#--------------------------- Bbduk parameters ---------------------------#
# Input parameters
qin: 'auto'
reads: -1
samplerate: 1
# Processing parameters
k: 27
rcomp: 't'
maskmiddle: 't'
minkmerhits: 1
minkmerfraction: 0.0
mincovfraction: 0.0
hammingdistance: 0
qhdist: 0
editdistance: 0
hammingdistance2: 0
qhdist2: 0
editdistance2: 0
forbidn: 'f'
# Trimming/filtering/masking parameters
ktrim: 'f'
ktrimtips: 0
maskfullycovered: 'f'
mink: 0
qtrim: 'f'
trimq: 6
minlength: 10
minlengthfraction: 0
minavgquality: 0
minbasequality: 0
maxns: -1
minconsecutivebases: 0
trimpad: 0
trimbyoverlap: 'f'
strictoverlap: 't'
minoverlap: 14
mininsert: 40
trimpairsevenly: 'f'
forcetrimleft: 0
forcetrimright: 0
forcetrimright2: 0
forcetrimmod: 0
restrictleft: 0
restrictright: 0
mingc: 0
maxgc: 1
tossjunk: 'f'


#--------------------------- Trim-Galore parameters ---------------------------#
quality: 20
quality_encoding: 'phred33'  # options: phred33 or phred64
adapter_sequence_1: null  # Or specify the sequence, for example 'GATCGTCGGACT'
adapter_sequence_2: null  # This is ignored in single-end reads. If not specified for paired-end reads, <adapter_sequence_1> will be applied on both reads.
specific_adapters: 'illumina'  # options are: 'illumina', 'stranded_illumina', 'nextera', 'small_rna', 'bgiseq'. Can only be none if adapter_sequence_1 and/or adapter_sequence_2 are specified
max_length: null
stringency: 1
error_rate: 0.1
length: 20
maxn: null
trim_n: false  # either true or false
trim_1: false  # either true or false
clip_R1: null
clip_R2: null
three_prime_clip_R1: null
three_prime_clip_R2: null
nextseq_quality: null  # only specify the qualty with nextseq and novaseq reads (replaces <quality> parameter)
hardtrim5: null
hardtrim3: null


#--------------------------- STAR parameters ---------------------------#
# Run parameters
runRNGseed: 777
# Genome Indexing Parameters - only used with –runMode genomeGenerate
genomeChrBinNbits: 18
genomeSAindexNbases: 12
genomeSAsparseD: 1
genomeSuffixLengthMax: -1
# Splice Junctions Database
sjdbGTFfeatureExon: 'exon'
sjdbGTFtagExonParentTranscript: 'transcript_id'
sjdbGTFtagExonParentGene: 'gene_id'
sjdbGTFtagExonParentGeneName: 'gene_name'
sjdbGTFtagExonParentGeneType: 'gene_type gene_biotype'
sjdbOverhang: 100
sjdbScore: 2
sjdbInsertSave: 'Basic'
readMapNumber: -1
readMatesLengthsIn: 'NotEqual'
readQualityScoreBase: 33
# Read Clipping
clipAdapterType: 'Hamming'
clip3pNbases: 0
clip3pAdapterSeq: null
clip3pAdapterMMp: 0.1
clip3pAfterAdapterNbases: 0
clip5pNbases: 0
# Output: General
outReadsUnmapped: 'None'
outQSconversionAdd: 0
outMultimapperOrder: 'Old_2.4'
# Output: SAM and BAM
outSAMmode: 'Full'
outSAMstrandField: 'None'
outSAMattributes: 'Standard'
outSAMattrIHstart: 1
outSAMunmapped: 'None'
outSAMprimaryFlag: 'OneBestScore'
outSAMreadID: 'Standard'
outSAMmapqUnique: 255
outSAMflagOR: 0
outSAMflagAND: 65535
outSAMmultNmax: -1
outSAMtlen: 1
outBAMcompression: 1
# Output Filtering
outFilterType: 'Normal'
outFilterMultimapScoreRange: 1
outFilterMultimapNmax: 10
outFilterMismatchNmax: 10
outFilterMismatchNoverLmax: 0.3
outFilterMismatchNoverReadLmax: 1.0
outFilterScoreMin: 0
outFilterScoreMinOverLread: 0.66
outFilterMatchNmin: 0
outFilterMatchNminOverLread: 0.66
outFilterIntronMotifs: 'None'
outFilterIntronStrands: 'RemoveInconsistentStrands'
# Output Filtering: Splice Junctions
outSJfilterReads: 'All'
outSJfilterOverhangMin: '30 12 12 12'
outSJfilterCountUniqueMin: '3 1 1 1'
outSJfilterCountTotalMin: '3 1 1 1'
outSJfilterDistToOtherSJmin: '10 0 5 10'
outSJfilterIntronMaxVsReadN: '50000 100000 200000'
# Scoring
scoreGap: 0
scoreGapNoncan: -8
scoreGapGCAG: -4
scoreGapATAC: -8
scoreGenomicLengthLog2scale: -0.25
scoreDelOpen: -2
scoreDelBase: -2
scoreInsOpen: -2
scoreInsBase: -2
scoreStitchSJshift: 1
# Alignments and Seeding
seedSearchStartLmax: 50
seedSearchStartLmaxOverLread: 1.0
seedSearchLmax: 0
seedMultimapNmax: 10000
seedPerReadNmax: 1000
seedPerWindowNmax: 50
seedNoneLociPerWindow: 10
seedSplitMin: 12
seedMapMin: 5
alignIntronMin: 21
alignIntronMax: 0
alignMatesGapMax: 0
alignSJoverhangMin: 5
alignSJstitchMismatchNmax: '0 -1 0 0'
alignSJDBoverhangMin: 3
alignSplicedMateMapLmin: 0
alignSplicedMateMapLminOverLmate: 0.66
alignWindowsPerReadNmax: 10000
alignTranscriptsPerWindowNmax: 100
alignTranscriptsPerReadNmax: 10000
alignEndsType: 'Local'
alignEndsProtrude: '0 ConcordantPair'
alignSoftClipAtReferenceEnds: 'Yes'
alignInsertionFlush: 'None'
# Paired-End reads
peOverlapNbasesMin: 0
peOverlapMMp: 0.01
# Windows, Anchors, Binning
winAnchorMultimapNmax: 50
winBinNbits: 16
winAnchorDistNbins: 9
winFlankNbins: 4
winReadCoverageRelativeMin: 0.5
winReadCoverageBasesMin: 0
quantMode: null
quantTranscriptomeBAMcompression: 1
quantTranscriptomeSAMoutput: 'BanSingleEnd_BanIndels_ExtendSoftclip'


#--------------------------- HTSEQ-COUNT parameters ---------------------------#
max_reads_in_buffer: 30000000
stranded: 'no'
minaqual: 10
feature_type: 'exon'
id_attribute: 'gene_id'
additional_attributes: null  # specify the additional attributes as a list of strings, e.g. ['gene_name', 'exon_number']
mode: 'union'
nonunique_mode: 'none'
secondary_alignments: 'score'
supplementary_alignments: 'score'
add_chromosome_info: false


#--------------------------- featureCounts parameters ---------------------------#
requireBothEndsMapped: false  # paired-end
countChimericFragments: false  # paired-end
minFragLength: 50
maxfragLength: 600
useMetaFeatures: false
isGTFAnnotationFile: true
attrType_GTF: 'gene_id'
juncCounts: false
isLongRead: false
countMultiMappingReads: false
allowMultiOverlap: false
checkFragLength: false  # only specify if <minFragLength> and <maxFragLength> are specified, paired-end
minMQS: 0
isStrandSpecific: 0
featureType_GTF: 'exon'  # If more than one feature type is provided, they should be separated by ',' (no space)
byReadGroup: false
countReadPairs: false  # paired-end
autosort: false  # paired-end
attrType_GTF_extra: null  # If more than one feature type is provided, they should be separated by ',' (no space)
fraction: false  # must be specified with <countMultiMappingReads> or <alloqMultiOverlap> or both
fracOverlap: 0
fracOverlapFeature: 0
ignoreDup: false
largestOverlap: false
minOverlap: 1
nonOverlap: null
nonOverlapFeature: null
nonSplitOnly: false
primaryOnly: false
read2pos: null
readExtension3: 0
readExtension5: 0
readShiftSize: 0
readShiftType: 'upstream'
splitOnly: false


#--------------------------- HISAT2-build parameters ---------------------------#
hisat2_index_prefix: 'genome'  # if not specified, the default 'genome' will be used
large_index: false
noauto: false  # If specified as true, must specify values for <bmax>/<bamxdivn> and <dcv> parameters
bmax: null
bmaxdivn: null  # if both <bmax> and <bmaxdivn> are specified, the value for <bmaxdivn> will override the value specified for <bmax>
dcv: null  # must be a power of 2 no greater than 4096
nodc: false
noref: false
justref: false
offrate: null
ftabchars: null
localoffrate: null
localftabchars: null
seed: null
cutoff: null


#--------------------------- HISAT2 parameters ---------------------------#
# Input options
skip: null
upto: null
trim5: null
trim3: null
phred_quality: 'phred33'  # options are: phred33 or phred64. If not specified, default is phred33
solexa_quals: false
int_quals: false
# Alignment options
n_ceil_func: null
ignore_quals: false
norc: false
nofw: false
# Scoring options
mismatch_penalties: null  # if specified, should be integers separated by a comma ',' no spaces
soft_clipping: null  # if specified, should be integers separated by a comma ',' no spaces
no_softclip: false
n_penalty: null
read_gap_penalty: null
reference_gap_penalty: null
score_min_func: null
# Spliced alignment options
pen_cansplice: null
pen_noncansplice: null
pen_canintronlen: null
pen_noncanintronlen: null
min_intronlen: null
max_intronlen: null
no_temp_splicesite: false
no_spliced_alignment: false
rna_strandness: null
transcriptome_mapping_only: false
downstream_transcriptome_assembly: false
dta_cufflinks: false
avoid_pseudogene: false
no_templatelen_adjustment: false
# Reporting options
num_alignments_per_read: null
max_seeds: null
report_all_alignments: false
report_secondary_alignments: false
# Paired-end options
min_fragment_length: null
max_fragment_length: null
mate_orientations: null  # options are: fr, rf, or ff
no_mixed: false
no_discordant: false
# Performance options
index_offrate: null
reorder: false
# Other options
rng_seed: null
non_deterministic: false


#--------------------------- SALMON QUASI MAPPING MODE parameters ---------------------------#
# Used with making the reference index
kmer_size: 31
# Basic options
seqBias: false
gcBias: false
posBias: false
incompatPrior: null
meta: false
discardOrphansQuasi: false
consensusSlack: null  # 0.349999994
preMergeChainSubThresh: null  # 0.75
postMergeChainSubThresh: null  # 0.90000000000000002
orphanChainSubThresh: null  # 0.94999999999999996
scoreExp: null  # 1
minScoreFraction: null
mismatchSeedSkip: null
disableChainingHeuristic: false
match_score: null  # 2
mismatch_score: null  # -4
gap_open_score: null  # 6
gap_extension_score: null  # 2
bandwidth: null  # 15
allowDovetail: false
recoverOrphans: false
miminBT2: false
mimicStrictBT2: false
softclip: false
softclipOverhangs: false
fullLengthAlignment: false
hardFilter: false
minAlnProb: null
writeQualities: false
hitFilterPolicy: null
# Advanced options
alternativeInitMode: false
skipQuant: false
dumpEq: false
dumpEqWeights: false
minAssignedFrags: null
reduceGCMemory: false
biasSpeedSamp: null  # 5
fldMax: null  # 1000
fldMean: null  # important for single-end reads, sets the expected mean fragment length (as it can't be estimated with single-end reads)
fldSD: null  # same with fldMean, but this specifies the expected standard deviation of the fragment length
maxOccsPerHit: null
maxReadOcc: null
noLengthCorrection: false
noEffectiveLengthCorrection: false
noSingleFragProb: false
noFragLengthDist: false
noBiasLengthThreshold: false
numBiasSamples: null
numAuxModelSamples: null
numPreAuxModelSamples: null
useEM: false
useVBOpt: true
rangeFactorizationBins: null
numGibbsSamples: null
noGammaDraw: false
numBootstraps: null
bootstrapReproject: false
thinningFactor: null
perTranscriptPrior: false
perNucleotidePrior: false
sigDigits: null
vbPrior: null


#--------------------------- KALLISTO index parameters ---------------------------#
kmer_length: null
make_unique: false
fasta_contains_aa: false
distinguish: false
minimizers_length: null
ec_max_size: null


#--------------------------- KALLISTO quant parameters ---------------------------#
num_bootstrap_samples: null
bootstrap_seed: null
plaintext: false
single_overhang: false
fr_stranded: false
rf_stranded: false
mean_fragment_length: 200  # estimated for paired-end reads, must be used for single-end reads (200)
sd_fragment_length: 70  # estimated for paired-end reads, must be used for single-end reads (70)


# General Splicing parameters
individualSplicingAnalysis: true
differentialSplicingAnalysis: true


#--------------------------- MAJIQ build parameters ---------------------------#
min_experiments: null
# Junction filters options
junction_minreads: null
junction_minpos: null
# Denovo junctions options
min_denovo_reads: null
disable_denovo: false
# Intron options
intron_read_pos_bins: null
min_intronic_cov: null
disable_ir: false
disable_denovo_ir: false
annotated_ir_always: false
# Simplifier options
enable_simplifier: false
simplify_psi: null
simplify_min_experiments: null
simplify_annotated: null
simplify_denovo: null
simplify_ir: null
# Bootstrap coverage sampling options
markstacks: null
num_bootstrap_read_coverage: null
# Advanced options
permissive: false
dump_constitutive: false
dump_coverage: false


#--------------------------- MAJIQ psi parameters ---------------------------#
minreads_psi: null
minpos_psi: null
min_experiments_psi: null


#--------------------------- MAJIQ deltapsi parameters ---------------------------#
minreads_deltapsi: null
minpos_deltapsi: null
min_experiments_deltapsi: null
psi_binsize: null
default_prior: false
prior_minreads: null
prior_minnonzero: null
prior_iter: null


#--------------------------- Voila modulize parameters for majiq psi files ---------------------------#
psi_ignore_inconsistent_group_errors: false
psi_only_binary: false
psi_untrimmed_exons: false
psi_show_all: false
# Limit the number of data processed to a specific target subset
psi_gene_ids_to_process_only: null  # provide as a string of gene_ids separated by a space, e.g. "gene_1 gene_2 gene_3"
psi_debug_num_genes: null
# Alternative use cases / run modes for specialized applications of modulizer
psi_output_mpe: false
psi_putative_multi_gene_regions: false
# Include or exclude junctions / modules based on structure or data availability
psi_keep_constitutive: false
psi_keep_no_lsvs_modules: false
psi_keep_no_lsvs_junctions: false
# Options for 'decomplexifier': removing junctions based on simple criteria prior to creating modules
decomplexify_psi_threshold: null
psi_decomplexify_reads_threshold: null


#--------------------------- Voila modulize parameters for majiq deltapsi files ---------------------------#
deltapsi_ignore_inconsistent_group_errors: false
deltapsi_only_binary: false
deltapsi_untrimmed_exons: false
deltapsi_show_all: false
heatmap_selection: null  # Default is "shortest_junction", other option is "abs_dpsi"
# Limit the number of data processed to a specific target subset
deltapsi_gene_ids_to_process_only: null  # provide as a string of gene_ids separated by a space, e.g. "gene_1 gene_2 gene_3"
deltapsi_debug_num_genes: null
# Alternative use cases / run modes for specialized applications of modulizer
deltapsi_output_mpe: false
deltapsi_putative_multi_gene_regions: false
# Include or exclude junctions / modules based on structure or data availability
deltapsi_keep_constitutive: false
deltapsi_keep_no_lsvs_modules: false
deltapsi_keep_no_lsvs_junctions: false
# Options for 'decomplexifier': removing junctions based on simple criteria prior to creating modules
decomplexify_deltapsi_threshold: null
deltapsi_decomplexify_reads_threshold: null
# Adjust the parameters used for determining whether a junction / module is changing or non-chnaging based on dpsi or heterogen file inputs
changing_between_group_dpsi: null
non_changing_between_group_dpsi: null
changing_between_group_dpsi_secondary: null
# Adjust the parameters used for determining whether a junction / module is changing or non-changing based on dpsi file inputs
probability_changing_threshold: null
probability_non_changing_threshold: null


#--------------------------- rMats parameters ---------------------------#
libType: null
readLength: 100  # required parameter
#--------------------------- rMats individual parameters ---------------------------#
ind_variable_read_length: true
ind_anchorLength: null
ind_tophatAnchor: null
ind_cstat: null
ind_task: null
ind_statoff: false
ind_paired_stats: false
ind_novelSS: false
ind_mil: null
ind_mel: null
#--------------------------- rMats differential parameters ---------------------------#
diff_variable_read_length: false
diff_anchorLength: null
diff_tophatAnchor: null
diff_cstat: null
diff_task: null
diff_statoff: false
diff_paired_stats: false
diff_novelSS: false
diff_mil: null
diff_mel: null


# RSEM parameters
rsem_index_prefix: 'rsem_reference'
strandedness: 'none'
fragment_length_mean: -1  # used only for single-end reads, change the value if you know it
fragment_length_sd: 0  # used only for single-end reads, change the value if you know it
